# Run Metadata Template
# Copy this for new runs, fill in values

run_id: "{MMDD}-{slug}-{hash}"
task_type: scout|plan|build|review
task_description: "Description of what this run does"
started_at: "ISO8601 timestamp"
model: "claude-sonnet-4"
config_hash: null  # Optional: for safety verification